[package]
name = "arr4com"
version = "0.1.0"
edition = "2021"


[lib]
name = "arr4com"
path = "src/lib.rs"

[[bin]]
name = "arr4combin"
path = "src/bin.rs"


[dependencies]
rustacuda = "0.1"
rustacuda_core = "0.1"
rustacuda_derive = "0.1"
